### ISSUE TITLE
Presentation slides

### ISSUE THREAD

**Issue by sadok-f** [shutefan/kubernetes-security-presentation#1]
Hi @shutefan ,
Thank you for putting this presentation online, it is very good material.
Is that possible to have the slides as well from the meetup?

Thank you again.
Best,
Sadok

**Comment by bippityboppity** [comment]
Hi @sadok-f, unfortunately there are no slides as I did the whole presentation "hands-on"!

**Comment by shutefan** [comment]
Hi @sadok-f, unfortunately there are no slides as I did the whole presentation "hands-on"!

**Comment by sadok-f** [comment]
I see, no problem.
Thx for the material you shared anyway.
